spring :
  config :
    import:
      - optional:database.yml
      - optional:logging.yml
      - optional:application-secret.yml
  app:
    version: v1
  jwt:
    secret: testsecretabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
    jwtexpiration: 86400000
    authheader: Authorization
